name: test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]


jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        pip install cpplint
        apt-get install -qq valgrind
        apt-get install -qq libcurl4-openssl-dev

    - name: build
      run: |
        ./autogen.sh
        ./configure --enable-coverage

    - name: run tests
      run: make ci
